---
title: "589 project"
author: "all"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%OS')`"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

```{r}
setwd("Raw data")  # Replace with actual path
occurrence <- read.delim("occurrence.txt", header = TRUE, sep = "\t", quote = "", stringsAsFactors = FALSE)
str(occurrence)
```

```{r}
load("BC_Covariates.Rda")

DATA$Animal <- occurrence[, c("decimalLatitude", "decimalLongitude", "month")]

sapply(DATA, class)
DATA$Animal
names(DATA$Animal)[names(DATA$Animal) == "decimalLatitude"] <- "Y"
names(DATA$Animal)[names(DATA$Animal) == "decimalLongitude"] <- "X"
names(DATA$Animal)[names(DATA$Animal) == "month"] <- "Month"
animal_sf <- st_as_sf(DATA$Animal, coords = c("X", "Y"), crs = 4326)

# Step 3: Transform to BC Albers projection (EPSG:3005)
animal_proj <- st_transform(animal_sf, crs = 3005)

# Step 4: Extract projected coordinates
coords <- st_coordinates(animal_proj)

# Step 5: Add projected X/Y back into DATA$Animal
DATA$Animal$X <- coords[, "X"]
DATA$Animal$Y <- coords[, "Y"]
save(DATA, file = "BC_Animal.Rda")
DATA$Animal
```
